version: "2"
services:
  wordpress:
    image: wordpress:latest
    container_name: verification_wordpress
    volumes:
      - "./:/var/www/html"
      - "./.docker/backup:/tmp/backup"
      - "./.docker/log:/tmp/log"
    ports:
      - '8088:80'
    environment:
      WORDPRESS_DB_HOST: "db:3306"
    env_file: .env
    links:
      - db

  db:
    image: mysql:5.7
    container_name: verification_db
    volumes:
      - "db-data:/var/lib/mysql"
    env_file: .env

volumes:
  db-data:
