version: "2"
services:
  wordpress:
    image: wordpress:latest
    container_name: verification_wordpress
    volumes:
      - "$PWD:/var/www/html"
      - "$PWD/.docker/backup:/tmp/backup"
      - "$PWD/.docker/log:/tmp/log"
    ports:
      - '8088:80'
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: "db:3306"
    networks:
      - my_wordpress_network
    env_file: .env

  db:
    image: mysql:5.7
    container_name: verification_db
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
      - my_wordpress_network
    env_file: .env

volumes:
  db-data:

networks:
  my_wordpress_network:
